name: py39-G5000
channels:
  - conda-forge
dependencies:
  - python=3.9.2
  - pip
  - setuptools
  - xesmf
  - esmpy
  - netCDF4
  - xarray
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - pip:
    - --find-links https://download.pytorch.org/whl/cu111/torch_stable.html
    - torch==1.10.1+cu111
    - torchaudio==0.10.1+cu111
    - torchvision==0.11.2+cu111
    - certifi
    - cftime
    - imageio
    - lazy_loader
    - networkx
    - packaging
    - pillow
    - pydantic
    - tifffile
    - typing_extensions
    - toml
    - python-dotenv
    - rich