name: py312-local

channels:
  - conda-forge

dependencies:
  - python=3.12
  - pip
  - pip:
    - asttokens==2.4.1
    - certifi==2024.8.30
    - cfgv==3.4.0
    - cftime==1.6.4.post1
    - colorama==0.4.6
    - contourpy==1.3.0
    - cycler==0.12.1
    - distlib==0.3.9
    - executing==2.1.0
    - filelock==3.16.1
    - fonttools==4.54.1
    - fsspec==2024.10.0
    - icecream==2.1.3
    - identify==2.6.1
    - imageio==2.36.0
    - ipykernel==6.29.5
    - Jinja2==3.1.4
    - kaleido==0.2.1
    - kiwisolver==1.4.7
    - lazy_loader==0.4
    - MarkupSafe==3.0.2
    - matplotlib==3.9.2
    - mpmath==1.3.0
    - netCDF4==1.7.2
    - networkx==3.4.2
    - nodeenv==1.9.1
    - numpy==2.1.3
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - packaging==24.1
    - pandas==2.2.3
    - pillow==11.0.0
    - platformdirs==4.3.6
    - plotly==5.24.1
    - pre_commit==4.0.1
    - pydantic==2.10.3
    - Pygments==2.18.0
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.2
    - PyYAML==6.0.2
    - rich==13.9.4
    - ruff==0.7.2
    - scikit-image==0.24.0
    - scipy==1.14.1
    - setuptools==75.3.0
    - six==1.16.0
    - streamlit==1.41.0
    - sympy==1.13.1
    - tenacity==9.0.0
    - tifffile==2024.9.20
    - toml==0.10.2
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - triton==3.1.0
    - typing_extensions==4.12.2
    - tzdata==2024.2
    - virtualenv==20.27.1
    - wheel==0.44.0
    - xarray==2024.10.0
    - xesmf
    - esmpy
